<a href="https://colab.research.google.com/github/gabriel-ricardo-ADS/python-basics/blob/main/IA_b%C3%A1sico_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

In [3]:
from google import genai

client  = genai.Client()

In [4]:
resposta = client.models.generate_content(model = "gemini-3-flash-preview", contents= "O que é a Inteligência Artificial")

In [ ]:
print(resposta.text)

A **Inteligência Artificial (IA)** é um campo da ciência da computação que se dedica a criar sistemas e tecnologias capazes de realizar tarefas que, normalmente, exigiriam a inteligência humana.

Em termos simples, é a capacidade de uma máquina "pensar", aprender, tomar decisões e resolver problemas de forma autônoma ou semi-autônoma.

Para entender melhor, vamos dividir o conceito em alguns pontos principais:

---

### 1. Como a IA funciona?
Ao contrário de um software tradicional, que segue uma lista rígida de instruções (se acontecer A, faça B), a IA utiliza **algoritmos** e grandes volumes de dados para identificar padrões.

Os principais pilares são:
*   **Aprendizado de Máquina (Machine Learning):** É a capacidade de o sistema melhorar seu desempenho à medida que é exposto a mais dados. Ele "aprende" com a experiência.
*   **Redes Neurais:** Sistemas inspirados na estrutura do cérebro humano para processar informações em camadas complexas.
*   **Processamento de Linguagem Natural (PLN):** A habilidade de entender, interpretar e gerar a linguagem humana (como o ChatGPT faz).

### 2. Os Tipos de Inteligência Artificial
A IA costuma ser classificada em dois grandes grupos:
*   **IA Estreita ou Fraca (Narrow AI):** É a que temos hoje. Ela é projetada para realizar uma tarefa específica (ex: recomendar um filme, reconhecer um rosto ou jogar xadrez). Ela não tem consciência nem inteligência fora daquela função.
*   **IA Geral ou Forte (AGI):** É uma inteligência teórica que seria capaz de realizar qualquer tarefa intelectual que um ser humano faz. Ainda não existe e é tema de muitos debates científicos e éticos.
*   **IA Generativa:** Uma evolução recente que consegue **criar** conteúdos novos (textos, imagens, músicas, vídeos) a partir de comandos, em vez de apenas analisar dados existentes.

### 3. Exemplos do dia a dia
Você provavelmente já usa IA várias vezes ao dia sem perceber:
*   **Assistentes Virtuais:** Alexa, Siri e Google Assistente.
*   **Recomendações:** O que a Netflix sugere para você assistir ou o que o Instagram mostra no seu feed.
*   **Filtros de Spam:** Seu e-mail identifica sozinho o que é lixo eletrônico.
*   **Mapas e GPS:** O Waze ou Google Maps calculam a melhor rota prevendo o trânsito.
*   **Reconhecimento Facial:** Para desbloquear o celular ou confirmar pagamentos.

### 4. Por que a IA é importante?
A IA permite processar uma quantidade de dados que seria impossível para um humano analisar em tempo útil. Isso traz avanços em áreas como:
*   **Medicina:** Diagnósticos mais precoces de câncer através de análise de imagens.
*   **Meio Ambiente:** Previsão de desastres naturais e otimização do uso de energia.
*   **Indústria:** Robôs que trabalham com precisão milimétrica e sem cansaço.

### 5. Desafios e Ética
Apesar dos benefícios, a IA traz preocupações:
*   **Substituição de Empregos:** Automatização de funções humanas.
*   **Privacidade:** Como nossos dados são usados para treinar esses sistemas.
*   **Vieses (Preconceitos):** Se a IA for treinada com dados que contêm preconceitos humanos, ela pode reproduzir e amplificar esses comportamentos.

**Resumo:** A Inteligência Artificial não é "mágica", mas sim matemática avançada aplicada a computadores para que eles possam simular o raciocínio humano e nos ajudar a resolver problemas complexos.

In [5]:
chat_bot = client.chats.create(model = "gemini-2.5-flash")

In [ ]:
resposta = chat_bot.send_message("O que é a Inteligência Artificial")

In [ ]:
print(resposta.text)

Parece que você enviou a mesma pergunta! Vou resumir a resposta de uma forma ainda mais direta e simples para complementar o que expliquei anteriormente.

De forma bem objetiva, **Inteligência Artificial (IA)** é a tecnologia que permite que computadores e máquinas "aprendam" a realizar tarefas que antes só humanos conseguiam fazer.

### A grande diferença entre um programa comum e uma IA:
*   **Programa Comum:** Funciona como uma **receita de bolo rígida**. O programador diz exatamente o que fazer: "Se o usuário clicar aqui, faça aquilo". Ele não sai do roteiro.
*   **Inteligência Artificial:** Funciona como um **aluno curioso**. Em vez de regras fixas, você dá a ela milhares de exemplos (dados). Ela analisa esses exemplos, entende os padrões e aprende a tomar decisões ou criar coisas sozinha.

### Três formas como ela se manifesta hoje:

1.  **IA Preditiva:** Analisa o passado para prever o futuro (ex: o banco que detecta uma compra suspeita no seu cartão porque não combina com seu hábito).
2.  **IA Generativa:** Cria coisas novas a partir do que aprendeu (ex: o **ChatGPT** que escreve textos ou o **Midjourney** que cria imagens).
3.  **IA de Reconhecimento:** Identifica padrões visuais ou sonoros (ex: o desbloqueio facial do celular ou a Alexa entendendo sua voz).

### Para que serve, no final das contas?
A IA serve para **processar informações em uma velocidade e escala que nenhum ser humano conseguiria**. Ela é uma ferramenta de auxílio que serve para automatizar o trabalho chato, resolver problemas complexos e criar novas possibilidades na medicina, na arte, na educação e na indústria.

**Gostaria de saber sobre algum ponto específico, como o funcionamento do ChatGPT ou o impacto da IA nos empregos?**

In [ ]:
resposta = chat_bot.send_message("Quando foi criado o Gemini")
print(resposta.text)

O **Gemini** (este modelo com o qual você está conversando) teve um lançamento dividido em duas fases importantes:

### 1. O lançamento do modelo (Dezembro de 2023)
O Google anunciou e lançou oficialmente a primeira versão do modelo Gemini (o "motor" da inteligência artificial) no dia **6 de dezembro de 2023**.
*   Naquele momento, ele foi integrado ao **Bard** (que era o nome anterior do chatbot do Google) para torná-lo mais inteligente.
*   Ele foi apresentado em três tamanhos: *Ultra* (para tarefas complexas), *Pro* (para uso geral) e *Nano* (para dispositivos móveis).

### 2. A mudança de nome e o aplicativo (Fevereiro de 2024)
No dia **8 de fevereiro de 2024**, o Google fez uma mudança completa de marca:
*   O chatbot **Bard** deixou de existir e passou a se chamar oficialmente **Gemini**.
*   Foi lançado o aplicativo dedicado para Android e a integração no iOS.
*   Foi lançada a versão mais poderosa, o Gemini Advanced (baseado no modelo Ultra 1.0).

### O contexto histórico:
Embora o nome "Gemini" seja recente, ele é o resultado de anos de pesquisa do Google. Ele surgiu da fusão de dois grandes laboratórios de IA do Google: o **Google Brain** e a **DeepMind**, que se uniram em 2023 especificamente para criar esta nova geração de modelos capazes de entender não só texto, mas também imagens, áudio, vídeos e códigos de programação (o que chamamos de IA multimodal).

**Resumindo:** O Gemini como tecnologia nasceu no final de **2023**, mas como o serviço/assistente que você acessa hoje, ele se consolidou em **fevereiro de 2024**.

In [ ]:
chat_bot.get_history()

[UserContent(
   parts=[
     Part(
       text='O que é a Inteligência Artificial'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text="""A **Inteligência Artificial (IA)** é um campo da ciência da computação que se dedica a criar sistemas e máquinas capazes de realizar tarefas que, normalmente, exigiriam inteligência humana.

 Em termos simples, é a capacidade de um computador "pensar", "aprender" e "tomar decisões" com base em dados.

 Aqui estão os pontos principais para entender o que é a IA:

 ### 1. Como ela funciona?
 Diferente de um software comum, que segue uma lista rígida de instruções (se acontecer A, faça B), a IA utiliza **algoritmos** e modelos matemáticos para identificar padrões em grandes quantidades de dados.
 *   **Aprendizado de Máquina (Machine Learning):** É a técnica mais comum. Em vez de programar cada regra, você fornece dados ao sistema e ele "aprende" sozinho a identificar padrões.
 *   **Redes Neurais e Deep Learning:** São sistemas inspirados na estrutura do cérebro humano, usados para tarefas complexas como reconhecimento de voz e tradução automática.

 ### 2. Os dois tipos principais de IA
 *   **IA Limitada ou Estreita (Narrow AI):** É a que temos hoje. Ela é projetada para realizar uma tarefa específica muito bem (ex: filtrar spam, recomendar filmes na Netflix ou jogar xadrez). Ela não tem consciência nem inteligência fora daquela função.
 *   **IA Geral (AGI):** É uma inteligência de nível humano, capaz de aprender e realizar qualquer tarefa intelectual que um ser humano faz. Por enquanto, a AGI ainda pertence ao campo da ficção científica e da pesquisa teórica.

 ### 3. Exemplos no dia a dia
 Você provavelmente já usa IA várias vezes ao dia sem perceber:
 *   **Assistentes de voz:** Siri, Alexa e Google Assistente.
 *   **Algoritmos de redes sociais:** Que decidem o que aparece no seu feed.
 *   **Reconhecimento facial:** Para desbloquear o celular.
 *   **IA Generativa:** Ferramentas como o **ChatGPT** (que cria textos), o **Midjourney** (que cria imagens) ou o **Suno** (que cria músicas).
 *   **Carros autônomos:** Como os da Tesla ou Waymo.

 ### 4. Por que a IA é importante agora?
 A IA não é um conceito novo (ela surgiu nos anos 50), mas explodiu nos últimos anos devido a três fatores:
 1.  **Poder de processamento:** Computadores ficaram muito mais rápidos.
 2.  **Big Data:** Temos uma quantidade imensa de dados digitais disponíveis para "treinar" essas máquinas.
 3.  **Algoritmos avançados:** Novas descobertas matemáticas permitiram criar modelos muito mais eficientes.

 ### 5. Desafios e Ética
 Apesar dos benefícios, a IA traz debates importantes:
 *   **Substituição de empregos:** Automação de tarefas repetitivas.
 *   **Viés (Preconceito):** Se os dados usados para treinar a IA forem parciais, a IA também será.
 *   **Privacidade:** Como nossos dados estão sendo usados.

 **Resumo:** A Inteligência Artificial é uma ferramenta poderosa que tenta simular processos cognitivos humanos para resolver problemas, automatizar tarefas e criar coisas novas de forma extremamente rápida.""",
       thought_signature=b"\x12\xc4\r\n\xc1\r\x01\xbe>\xf6\xfbo\xaeh\xaf9'f\xa5\xadC\xf9C\xc6\x96\x9fh\x91-\xcca\x07\xce\xff\xe3\xdd\xf0\x1bB\xec\xad\xf9\x12\xae\xdf\xdc\xfccL\xd9B\r\x18\xd9]s\xd6\xe6\xbd<\xff\xa3\xdf\xc0I\x0b\xe3\xc4\xdd\xd8\xe4\xbd0\x91\xb1\xaf\xb0\xfd\x82\tb\xc2\xf68\xbb`\xea\xc9\x95\xd6.Fqb\xee\xdb\xb6...'
     ),
   ],
   role='model'
 ),
 UserContent(
   parts=[
     Part(
       text='O que é a Inteligência Artificial'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text="""Parece que você enviou a mesma pergunta! Vou resumir a resposta de uma forma ainda mais direta e simples para complementar o que expliquei anteriormente.

 De forma bem objetiva, **Inteligência Artificial (IA)** é a tecnologia que permite que computadores e máquinas "aprendam" a realizar tarefas que antes só humanos conseguiam fazer.

 ### A grande diferença entre um programa comum e uma IA:
 *   **Programa Comum:** Funciona como uma **receita de bolo rígida**. O programador diz exatamente o que fazer: "Se o usuário clicar aqui, faça aquilo". Ele não sai do roteiro.
 *   **Inteligência Artificial:** Funciona como um **aluno curioso**. Em vez de regras fixas, você dá a ela milhares de exemplos (dados). Ela analisa esses exemplos, entende os padrões e aprende a tomar decisões ou criar coisas sozinha.

 ### Três formas como ela se manifesta hoje:

 1.  **IA Preditiva:** Analisa o passado para prever o futuro (ex: o banco que detecta uma compra suspeita no seu cartão porque não combina com seu hábito).
 2.  **IA Generativa:** Cria coisas novas a partir do que aprendeu (ex: o **ChatGPT** que escreve textos ou o **Midjourney** que cria imagens).
 3.  **IA de Reconhecimento:** Identifica padrões visuais ou sonoros (ex: o desbloqueio facial do celular ou a Alexa entendendo sua voz).

 ### Para que serve, no final das contas?
 A IA serve para **processar informações em uma velocidade e escala que nenhum ser humano conseguiria**. Ela é uma ferramenta de auxílio que serve para automatizar o trabalho chato, resolver problemas complexos e criar novas possibilidades na medicina, na arte, na educação e na indústria.

 **Gostaria de saber sobre algum ponto específico, como o funcionamento do ChatGPT ou o impacto da IA nos empregos?**""",
       thought_signature=b'\x12\xf3\x12\n\xf0\x12\x01\xbe>\xf6\xfb\x02\xff\xfe\xaa\xb9=\xaa\x80\xf8\x99\x8a\x1a\xb1`\xeb\xf9\xc4\n\x80\xc7\x8a\x96\x1e\xb0\x95Y\x1b!.Eg\x95]\xe3\x16A\xbeH\x05[\xb91%\xbe\xf2\x89\xd2\x1e\xde,\r4k\x04\x0bN\xcc6\x8a\xad\n\xcbF\x0f*\n\xc2}Q\xc67\x03\x95=\xe4}]Gm64\xb4\xb6\xb4\xb2\x0f...'
     ),
   ],
   role='model'
 ),
 UserContent(
   parts=[
     Part(
       text='Quando foi criado o Gemini'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text="""O **Gemini** (este modelo com o qual você está conversando) teve um lançamento dividido em duas fases importantes:

 ### 1. O lançamento do modelo (Dezembro de 2023)
 O Google anunciou e lançou oficialmente a primeira versão do modelo Gemini (o "motor" da inteligência artificial) no dia **6 de dezembro de 2023**.
 *   Naquele momento, ele foi integrado ao **Bard** (que era o nome anterior do chatbot do Google) para torná-lo mais inteligente.
 *   Ele foi apresentado em três tamanhos: *Ultra* (para tarefas complexas), *Pro* (para uso geral) e *Nano* (para dispositivos móveis).

 ### 2. A mudança de nome e o aplicativo (Fevereiro de 2024)
 No dia **8 de fevereiro de 2024**, o Google fez uma mudança completa de marca:
 *   O chatbot **Bard** deixou de existir e passou a se chamar oficialmente **Gemini**.
 *   Foi lançado o aplicativo dedicado para Android e a integração no iOS.
 *   Foi lançada a versão mais poderosa, o Gemini Advanced (baseado no modelo Ultra 1.0).

 ### O contexto histórico:
 Embora o nome "Gemini" seja recente, ele é o resultado de anos de pesquisa do Google. Ele surgiu da fusão de dois grandes laboratórios de IA do Google: o **Google Brain** e a **DeepMind**, que se uniram em 2023 especificamente para criar esta nova geração de modelos capazes de entender não só texto, mas também imagens, áudio, vídeos e códigos de programação (o que chamamos de IA multimodal).

 **Resumindo:** O Gemini como tecnologia nasceu no final de **2023**, mas como o serviço/assistente que você acessa hoje, ele se consolidou em **fevereiro de 2024**.""",
       thought_signature=b'\x12\xed\x06\n\xea\x06\x01\xbe>\xf6\xfb>\xd3\xbe\xd4[ky\x10\xc7\xbd((\x95\x94Q0\x18[a2\xb8+\xf6\xf7s\xc7\x86O\n-R\xebeP\x82\xa1\x98\xf0\xd4\xd0\xf064OKA,\xa7\xe8\xc8\xe0X\x0c\xe6\xba\\J\x83\x17\xca\xaf\xa1\xdfhz(\xbd&Q\xe2!\x13"\x92A\x86\x04H%\xc5\xaaw\xc7"\xb0\x01...'
     ),
   ],
   role='model'
 )]

In [6]:
prompt = input("digite sua pergunta: ")

while prompt != "fim":
  resposta = chat_bot.send_message(prompt)
  print(resposta.text)
  print("\n")
  prompt = input("digite sua pergunta, ou diga 'fim' para finalizar: ")

digite sua pergunta: ola
Olá! Como vai?


digite sua pergunta, ou diga 'fim' para finalizar: fim

## Manipulando dados com Pandas

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("/content/meu_csv.csv")

In [10]:
df.head()

      nome  media
0      Ana    7.5
1   Carlos    8.2
2  Beatriz    9.1
3    Diogo    6.8
4  Eduarda    5.9

In [11]:
df.tail()

       nome  media
5  Fernanda    8.5
6   Gustavo    7.3
7    Helena    9.5
8      Igor    6.1
9   Juliana    8.9

In [12]:
lista_de_perguntas = [
    "Como funciona um motor V16?",
    "Como a gasolina vai ao motor?",
    "Como funciona a direção hidráulica?",
    "Quantos cavalos tem um Mclaren Senna?",
    "Quanto custa uma Ferrari Monza",
    "Qual o valor do IPVA no Brasil?",
    "Como calcular o gasto do motor?",
    "O que é a Inteligência Artificial",
    "Quando foi criado o Gemini",
    "Quantos anos tem Lebron James?"
]

with open("perguntas.txt", "w", encoding="utf-8") as arquivo:
  for pergunta in lista_de_perguntas:
    arquivo.write(pergunta + "\n")

In [13]:
lista_desafio = []

with open ("perguntas.txt", "r", encoding="utf-8") as arquivo:
  for linha in arquivo:
    lista_desafio.append(linha.strip())

print(lista_desafio)

['Como funciona um motor V16?', 'Como a gasolina vai ao motor?', 'Como funciona a direção hidráulica?', 'Quantos cavalos tem um Mclaren Senna?', 'Quanto custa uma Ferrari Monza', 'Qual o valor do IPVA no Brasil?', 'Como calcular o gasto do motor?', 'O que é a Inteligência Artificial', 'Quando foi criado o Gemini', 'Quantos anos tem Lebron James?']